spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/slr-database
    username: postgres
    password: postgres
  mail:
    host: maildev
    port: 1025
    username: test
    password: test
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000