spring:
  datasource:
    url: jdbc:postgresql://database:5432/slr-database
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: slrspot.welcome@gmail.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mail:
  enabled: true