spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${POSTGRESQL-SERVER}/${POSTGRESQL-DATABASE-NAME}?sslmode=require
    username: ${POSTGRESQL-USERNAME}
    password: ${POSTGRESQL-PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: slrspot.welcome@gmail.com
    password: ${SMTP-PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            credential:
              managed-identity-enabled: true
            endpoint: https://slrspot-secrets.vault.azure.net/

jwt:
  secret: ${JWT-SECRET}