spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: HSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
  datasource:
    url: jdbc:hsqldb:mem:scratchdb

mail:
  enabled: false