export const TITLE_SEARCH = "TITLE";
export const AUTHORS_SEARCH = "AUTHORS";
export const YEAR_SEARCH = "YEAR";
export const TITLE_AUTHORS_SEARCH = "TITLE_AUTHORS";
export const TITLE_YEAR_SEARCH = "TITLE_YEAR";
export const AUTHORS_YEAR_SEARCH = "AUTHORS_YEAR";
export const TITLE_AUTHORS_YEAR_SEARCH = "TITLE_AUTHORS_YEAR";
export const EVERYTHING_SEARCH = "EVERYTHING";