export const TITLE_ABSTRACT = "TITLE_ABSTRACT";
export const FULL_TEXT = "FULL_TEXT";
export const EXCLUDED = "EXCLUDED";
export const INCLUDED = "INCLUDED";
export const STUDY_STATUSES = [TITLE_ABSTRACT, FULL_TEXT, EXCLUDED, INCLUDED]; 