services:
  database:
    image: "postgres:14.2-alpine"
    container_name: slr-db
    # restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=slr-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    # networks:
    #   - slrspotnet
#    secrets:
#      - postgres_password

  app:
    build:
      context: ../slr_spot_backend
      dockerfile: Dockerfile
    # image: slr-java-docker
    container_name: slr-app
    ports:
      - "8080:8080"
    links:
      - database
    # networks:
    #   - slrspotnet
#    secrets:
#      - postgres_password

  frontend:
    build:
      context: ../slr_spot_frontend
      dockerfile: Dockerfile
    container_name: slr_spot_frontend
    ports:
      - 3000:3000

volumes:
  db_data:

#secrets:
#  postgres_password:
#    file: ./devsecrets/postgres_password

# networks:
#   slrspotnet:
#     driver: bridge