services:
  database:
    image: "postgres:14.2-alpine"
    container_name: slr-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=slr-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ../slr_spot_backend
      dockerfile: Dockerfile
    container_name: slr-app
    ports:
      - "8080:8080"
    links:
      - database
      - maildev

  frontend:
    build:
      context: ../slr_spot_frontend
      dockerfile: Dockerfile
    container_name: slr_spot_frontend
    ports:
      - 3000:3000

  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

volumes:
  db_data: